<?php

namespace AppBundle\Repository;

/**
 * PonyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PonyRepository extends \Doctrine\ORM\EntityRepository
{
}
